# Generated by Django 5.2.14 on 2026-05-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
