# Generated by Django 5.2.14 on 2026-05-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='duration',
        ),
    ]
