# Generated by Django 5.2.14 on 2026-05-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('genre', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=20)),
            ],
        ),
    ]
