# Generated by Django 5.2.14 on 2026-05-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
