# Generated by Django 5.2.14 on 2026-05-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentitem_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
